server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: false  #禁止向eureka注册服务，因为它自己本身就是服务器
#    fetchRegistry: false  #这里不需要抓取注册表
spring:
  application:
    name: ribbon_server
ping-server:
  ribbon:
    listOfServers: localhost:8762,localhost:8763
    ServerListRefreshInterval: 15000

